# Generated by Django 5.0.2 on 2024-02-27 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1993-03-28'),
            preserve_default=False,
        ),
    ]
